### ISSUE TITLE
Does not support server authentication

### ISSUE THREAD

**Issue by admsteck** [Badgerati/NotifyMeCI#11] opened 2016-06-15 15:34 UTC
Our Jenkins server is setup to require authentication before you can view jobs.  As it stands now when I try to add our jenkins server, the NotifyMeCI returns a 403 forbidden error since no authentication is sent with the request.

**Comment by Badgerati** [comment] 2016-06-15 18:02
Thanks for pointing this out, bit of an oversight on my part with only dealing with Jenkins servers that just let you view the jobs regardless; sorry!

I have a fix in place for this, so when you add/update the Jenkins server in NotifyMeCI, you can specify the authentication value of `<username>:<api_token or password>` if required.

I've tested this on my Jenkins server, and it works as intended with/without the auth tokens.

**Comment by Badgerati** [comment] 2016-06-15 18:11
@admsteck I've pushed the fix into the `Issue-11` branch for if you wish to test the fix yourself. If you're satisfied, let me know and I'll push the fix out.

**Comment by admsteck** [comment] 2016-06-15 19:04
@Badgerati That was quick!  Looks great and works as expected. Thanks.

**Comment by Badgerati** [comment] 2016-06-15 19:52
@admsteck No problem :) I'll get that pushed out now.

**Closed as completed** 2016-06-15 20:01 UTC
Labels: bug

**Comment by Badgerati** [comment] 2016-06-15 20:15
I've pushed v1.1.1.3 up to Chocolatey so should be available soon; the release binaries are also [here](https://github.com/Badgerati/NotifyMeCI/releases).
